import type { Metadata } from 'next';
import './globals.css';
import ClientModals from './clientModal';

export const metadata: Metadata = {
	title: '팬풀',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<ClientModals />
				<div className="w-full h-full relative overflow-hidden">{children}</div>
			</body>
		</html>
	);
}
